version: '3.8'

services:

  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-net

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - spring-net

  product-service:
    image: product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - spring-net

  order-service:
    image: order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - product-service
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
